version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/project-templates/content/umbraco-headless-bff"
    schedule:
      interval: "weekly"
      day: "friday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # This group catches ONLY Aspire Major moves
      aspire-major-deps:
        patterns: ["Aspire*"]
        update-types: ["major"]
      # This group catches everything else (including Aspire minor/patch)
      dotnet-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "friday"
    groups:
      all-deps:
        patterns: ["*"]
